$ErrorActionPreference = 'Stop'
$root = Join-Path $PSScriptRoot '../src/main/resources/assets/selarium/lang'
$translations = @{
    pt_br = @'
{
  "block.selarium.inscription_bench": "Bancada de Inscrição",
  "item.selarium.inscription_bench": "Bancada de Inscrição",
  "item.selarium.empty_scroll": "Pergaminho vazio",
  "item.selarium.attunement_scroll": "Pergaminho de sintonização",
  "item.selarium.ward_scroll": "Pergaminho de proteção",
  "gui.selarium.attunement_recipe": "Sintonização %s",
  "gui.selarium.inscription.status": "Estado da inscrição",
  "gui.selarium.inscription.select": "Escolha uma receita.",
  "gui.selarium.inscription.ready": "Pronto para inscrever.",
  "gui.selarium.inscription.empty_scroll": "Falta um pergaminho vazio.",
  "gui.selarium.inscription.dust": "Faltam as poeiras da receita.",
  "gui.selarium.inscription.catalyst": "Falta um catalisador.",
  "gui.selarium.inscription.milestone": "%s mana gasta · %s proteções · %s refinadas",
  "gui.selarium.inscription.field": "Alcance %s · %s mana/ciclo · %ss",
  "gui.selarium.inscription.ingredients": "Componentes",
  "gui.selarium.sigil.stats": "Alcance %s · %s mana/ciclo · %ss",
  "gui.selarium.sigil.requirements": "Poeiras necessárias",
  "gui.selarium.sigil.selected": "Proteção escolhida",
  "gui.selarium.sigil.active": "Campo ativo",
  "gui.selarium.sigil.inactive": "Campo inativo",
  "gui.selarium.sigil.mana": "Reserva: %s mana",
  "gui.selarium.sigil.quick_action": "Shift + clique: ativar/desativar",
  "gui.selarium.sigil.components": "Clique para retirar poeiras",
  "message.selarium.sigil.owner_only": "Apenas o dono pode alterar este sigilo.",
  "message.selarium.sigil.deactivate_first": "Desative o sigilo antes de alterar as poeiras.",
  "message.selarium.scroll.foreign": "Este pergaminho pertence a outra pessoa.",
  "message.selarium.scroll.invalid": "Este pergaminho está incompleto ou a proteção foi desativada.",
  "message.selarium.scroll.not_discovered": "Ative esta proteção em um sigilo antes de inscrevê-la.",
  "message.selarium.scroll.point_at_block": "Aponte para um bloco onde o campo será criado.",
  "message.selarium.scroll.duplicate": "Você já mantém esta proteção por pergaminho.",
  "message.selarium.scroll.limit": "Limite de dois campos móveis ou três fixos atingido.",
  "message.selarium.scroll.unloaded": "O local do campo ainda não está carregado.",
  "message.selarium.scroll.cast": "Campo de %s invocado.",
  "message.selarium.attunement.own_sigil": "Use o pergaminho em um sigilo seu.",
  "message.selarium.attunement.inactive_sigil": "Desative o sigilo antes do ritual.",
  "message.selarium.attunement.tier_order": "Este nível de mana não é o próximo a desbloquear.",
  "message.selarium.attunement.mana_spent": "Ainda falta mana gasta para este marco.",
  "message.selarium.attunement.wards": "Ative mais proteções distintas para este marco.",
  "message.selarium.attunement.refined": "Ative mais proteções refinadas para este marco.",
  "message.selarium.attunement.success": "Limite de %s mana desbloqueado!",
  "message.selarium.phasing.available": "Travessia disponível em blocos de phasing do Selarium.",
  "tooltip.selarium.scroll.creator": "Criador: %s",
  "tooltip.selarium.scroll.mobile": "Campo móvel: acompanha o criador",
  "tooltip.selarium.scroll.fixed": "Campo fixo: surge no local apontado",
  "tooltip.selarium.scroll.duration": "Duração: %ss · manutenção: %s mana/ciclo",
  "tooltip.selarium.attunement.limit": "Novo limite: %s mana",
  "tooltip.selarium.attunement.requirements": "Marcos: %s mana gasta, %s proteções, %s refinadas",
  "tooltip.selarium.attunement.cost": "Ritual: %s mana",
  "screen.selarium.warding_grimoire.overview.text": "O Grimório define quem seus sigilos e campos de pergaminho afetam. As regras são compartilhadas por todas as proteções do mesmo criador.",
  "screen.selarium.warding_grimoire.overview.safety": "Registre uma proteção ativando-a em um sigilo antes de inscrever seu pergaminho. Configurações de segurança do servidor têm prioridade.",
  "screen.selarium.codex.start.title": "Primeiros passos",
  "screen.selarium.codex.start.p1": "Procure geodos arcanos no subsolo. Aglomerados maduros fornecem cristais; o Moedor Arcano converte cristais em poeira arcana.",
  "screen.selarium.codex.start.p2": "Árvores arcanas podem indicar um geodo: siga a veia de pedra clara sob o tronco. Pétalas arcanas oferecem um pouco de poeira na superfície.",
  "screen.selarium.codex.start.p3": "Use poeira arcana sobre um bloco firme para criar um sigilo. Adicione poeiras especializadas para compor proteções.",
  "screen.selarium.codex.start.p4": "As 32 proteções continuam disponíveis por sigilos. A Bancada de Inscrição acrescenta pergaminhos e progressão.",
  "screen.selarium.codex.mana.title": "Mana",
  "screen.selarium.codex.mana.p1": "Proteções ativas pagam manutenção em ciclos. O pagamento usa a reserva do sigilo, tanques adjacentes e depois a mana do dono, quando permitido.",
  "screen.selarium.codex.mana.p2": "Seu limite inicial é 500. Rituais sucessivos liberam limites de 1.000, 2.500, 5.000 e 10.000; cada nível exige marcos e mana.",
  "screen.selarium.codex.mana.p3": "Mana gasta, proteções descobertas e níveis desbloqueados continuam registrados após morte, troca de dimensão e reinício.",
  "screen.selarium.codex.grinder.title": "Moedor Arcano",
  "screen.selarium.codex.grinder.p1": "O Moedor Arcano transforma cristais em poeira arcana e combina poeiras com reagentes para obter as variantes especializadas.",
  "screen.selarium.codex.grinder.p2": "Proteções refinadas exigem poeira refinada em todos os componentes especializados. A poeira Arcane permanece básica.",
  "screen.selarium.codex.recipes.title": "Receitas centrais",
  "screen.selarium.codex.recipes.p1": "Papel, linha e poeira arcana formam um pergaminho vazio. Use-o na Bancada de Inscrição com poeiras e catalisadores.",
  "screen.selarium.codex.recipes.p2": "Nove cristais formam um bloco arcano. Cristal arcano catalisa proteções básicas; bloco arcano catalisa as refinadas.",
  "screen.selarium.codex.recipes.p3": "Livro e poeira arcana formam o Codex. O Grimório também usa poeiras Binding e Focus.",
  "screen.selarium.codex.dusts.title": "Poeiras",
  "screen.selarium.codex.dusts.p1": "Arcane é a base. Aegis protege; Vital sustenta; Focus direciona; Binding prende; Echo percebe; Density ancora; Warp desloca; Veil oculta; Chrono altera o tempo.",
  "screen.selarium.codex.dusts.p2": "Poeiras básicas ou refinadas servem em receitas básicas. Receitas refinadas aceitam apenas variantes refinadas dos componentes especializados.",
  "screen.selarium.codex.sigils.title": "Sigilos",
  "screen.selarium.codex.sigils.p1": "Clique em um sigilo sem poeira para escolher entre as proteções compatíveis. A interface mostra requisitos, alcance, custo e duração.",
  "screen.selarium.codex.sigils.p2": "Shift + clique ativa ou desativa a proteção escolhida. A interface também retira componentes e devolve a poeira ao inventário ou ao chão.",
  "screen.selarium.codex.sigils.p3": "Um sigilo só pertence ao criador. Inscrever pergaminhos exige ter ativado a proteção em um sigilo antes.",
  "screen.selarium.codex.progression.title": "Progressão",
  "screen.selarium.codex.progression.p1": "1.000: gaste 250 mana e ative 3 proteções distintas. Inscreva Focus, Vital e Aegis básicas com um cristal arcano. Ritual: 250 mana.",
  "screen.selarium.codex.progression.p2": "2.500: gaste 1.200 mana e ative 6 proteções, 2 refinadas. Inscreva Focus, Vital e Binding refinadas com bastão de blaze e bloco arcano. Ritual: 700 mana.",
  "screen.selarium.codex.progression.p3": "5.000: gaste 4.000 mana e ative 10 proteções, 4 refinadas. Inscreva Warp, Veil e Focus refinadas com sopro do dragão e pérola do End. Ritual: 1.800 mana.",
  "screen.selarium.codex.progression.p4": "10.000: gaste 10.000 mana e ative 16 proteções, 8 refinadas. Inscreva Aegis, Echo e Chrono refinadas com estrela do Nether e fragmento de eco. Ritual: 4.000 mana.",
  "screen.selarium.codex.progression.p5": "Use o pergaminho de sintonização em um sigilo seu e inativo. O ritual valida os marcos novamente antes de cobrar mana.",
  "screen.selarium.codex.progression.p6": "O ritual pode usar reserva do sigilo, tanques adjacentes e mana do dono, nessa ordem. Falhas preservam o pergaminho e a mana.",
  "screen.selarium.codex.scrolls.title": "Pergaminhos",
  "screen.selarium.codex.scrolls.p1": "A Bancada de Inscrição tem pergaminho vazio, cinco posições de poeira, dois catalisadores e saída. Escolha a receita na lista.",
  "screen.selarium.codex.scrolls.p2": "Um pergaminho de proteção requer uma proteção já ativada por seu criador. Inscreve as poeiras da proteção e cristal arcano ou bloco arcano.",
  "screen.selarium.codex.scrolls.p3": "Cada pergaminho registra o UUID do criador. Apenas ele pode usá-lo. A invocação válida consome uma unidade e a primeira cobrança de mana.",
  "screen.selarium.codex.scrolls.p4": "Campos móveis acompanham o criador; os demais surgem no local apontado. Limites: dois móveis, três fixos e nenhuma proteção repetida.",
  "screen.selarium.codex.scrolls.p5": "O campo dura metade da duração do sigilo, paga a mesma manutenção e segue as regras do Grimório. Ao terminar, inicia seu tempo de espera.",
  "screen.selarium.codex.scrolls.p6": "Campos móveis pausam durante desconexão, seguem trocas de dimensão e acabam na morte. Campos fixos persistem no mundo até expirar.",
  "screen.selarium.codex.grimoire.title": "Grimório",
  "screen.selarium.codex.grimoire.p1": "O Codex ensina; o Grimório define alvos. Configure aliados, inimigos e categorias de entidades antes de ativar um campo.",
  "screen.selarium.codex.grimoire.p2": "O Grimório se vincula ao dono no primeiro uso e compartilha regras entre seus sigilos e pergaminhos.",
  "screen.selarium.codex.grimoire.p3": "Shift + clique em criaturas registra conhecimentos de alma. Ativar uma proteção registra seu padrão de forma permanente.",
  "screen.selarium.codex.grimoire.p4": "Configurações de segurança do servidor, proteção do dono e listas de permissão têm prioridade sobre as regras gerais.",
  "screen.selarium.codex.wards.title": "Proteções",
  "screen.selarium.codex.wards.p1": "Uma proteção é um campo contínuo. Cada ciclo paga manutenção e afeta alvos válidos dentro do alcance, respeitando limites de segurança.",
  "screen.selarium.codex.wards.p2": "As receitas abaixo mostram pureza mínima, alcance, manutenção e intervalo. Falta de poeira, mana, permissão ou tempo de espera impede a ativação.",
  "screen.selarium.codex.ward.entry": "%s: %s. Alcance %s, manutenção %s a cada %s ticks.",
  "screen.selarium.codex.tanks.title": "Tanques de Mana",
  "screen.selarium.codex.tanks.p1": "Tanques adjacentes sustentam sigilos e rituais depois da reserva do sigilo. O nível de mana fica visível nas quatro faces.",
  "screen.selarium.codex.tanks.p2": "Campos de pergaminho também usam fontes de mana próximas e a mana do criador durante a manutenção.",
  "screen.selarium.codex.geodes.title": "Geodos",
  "screen.selarium.codex.geodes.p1": "Geodos arcanos contêm pedra, blocos de cristal, blocos brotantes e aglomerados em quatro estágios.",
  "screen.selarium.codex.geodes.p2": "Aglomerados maduros produzem cristais quando colhidos; Toque Suave preserva o bloco. Fortuna pode aumentar os cristais.",
  "screen.selarium.codex.geodes.p3": "Mudas arcanas produzem árvores comuns. Árvores plantadas pelo jogador não criam novos geodos.",
  "screen.selarium.codex.ward_note.ambient_mana": "Gera mana com limite por ativação.",
  "screen.selarium.codex.ward_note.whispering": "Alerta o dono sobre intrusos.",
  "screen.selarium.codex.ward_note.spectral": "Revela intrusos com brilho.",
  "screen.selarium.codex.ward_note.bulwark": "Concede resistência a aliados.",
  "screen.selarium.codex.ward_note.rejuvenation": "Regenera aliados.",
  "screen.selarium.codex.ward_note.featherweight": "Reduz perigos de queda.",
  "screen.selarium.codex.ward_note.grounding": "Remove levitação e estabiliza aliados.",
  "screen.selarium.codex.ward_note.magnetism": "Atrai itens soltos.",
  "screen.selarium.codex.ward_note.banishment": "Afasta intrusos do campo.",
  "screen.selarium.codex.ward_note.eclipse": "Escurece a visão dos intrusos.",
  "screen.selarium.codex.ward_note.fertility": "Estimula reprodução animal.",
  "screen.selarium.codex.ward_note.citadel": "Ergue muralha temporária com passagem para aliados.",
  "screen.selarium.codex.ward_note.disruption": "Interrompe teletransportes.",
  "screen.selarium.codex.ward_note.cloaking": "Oculta o dono e desfaz alvos hostis.",
  "screen.selarium.codex.ward_note.accelerating": "Acelera plantas e filhotes.",
  "screen.selarium.codex.ward_note.efficiency": "Acelera fornalhas e o Moedor Arcano.",
  "screen.selarium.codex.ward_note.crushing": "Pressiona e enfraquece intrusos.",
  "screen.selarium.codex.ward_note.inversion": "Arremessa intrusos para cima.",
  "screen.selarium.codex.ward_note.aqualung": "Restaura ar e ajuda na água.",
  "screen.selarium.codex.ward_note.transmutation": "Converte itens específicos e oxida cobre.",
  "screen.selarium.codex.ward_note.tangible": "Forma barreira temporária com passagem para aliados.",
  "screen.selarium.codex.ward_note.sanctuary": "Impede surgimento de hostis.",
  "screen.selarium.codex.ward_note.bounty": "Pode acrescentar um item a um saque elegível.",
  "screen.selarium.codex.ward_note.immortal": "Impede uma morte de aliado por 1.200 ticks, cobrando 200 mana extra.",
  "screen.selarium.codex.ward_note.drain": "Drena intrusos, com geração limitada por ciclo.",
  "screen.selarium.codex.ward_note.soul_chain": "Propaga parte do dano entre intrusos.",
  "screen.selarium.codex.ward_note.stasis": "Retarda intrusos e projéteis.",
  "screen.selarium.codex.ward_note.maelstrom": "Puxa e sufoca intrusos.",
  "screen.selarium.codex.ward_note.decay": "Aplica deterioração aos intrusos.",
  "screen.selarium.codex.ward_note.deflection": "Desvia projéteis hostis.",
  "screen.selarium.codex.ward_note.silence": "Enfraquece e remove efeitos benéficos.",
  "screen.selarium.codex.ward_note.phasing": "Permite atravessar blocos de phasing do Selarium."
}
'@
    en_us = @'
{
  "block.selarium.inscription_bench": "Inscription Bench",
  "item.selarium.inscription_bench": "Inscription Bench",
  "item.selarium.empty_scroll": "Empty Scroll",
  "item.selarium.attunement_scroll": "Attunement Scroll",
  "item.selarium.ward_scroll": "Ward Scroll",
  "gui.selarium.attunement_recipe": "Attunement %s",
  "gui.selarium.inscription.status": "Inscription status",
  "gui.selarium.inscription.select": "Choose a recipe.",
  "gui.selarium.inscription.ready": "Ready to inscribe.",
  "gui.selarium.inscription.empty_scroll": "An empty scroll is missing.",
  "gui.selarium.inscription.dust": "Recipe dusts are missing.",
  "gui.selarium.inscription.catalyst": "A catalyst is missing.",
  "gui.selarium.inscription.milestone": "%s mana spent · %s wards · %s refined",
  "gui.selarium.inscription.field": "Range %s · %s mana/cycle · %ss",
  "gui.selarium.inscription.ingredients": "Ingredients",
  "gui.selarium.sigil.stats": "Range %s · %s mana/cycle · %ss",
  "gui.selarium.sigil.requirements": "Required dusts",
  "gui.selarium.sigil.selected": "Selected ward",
  "gui.selarium.sigil.active": "Field active",
  "gui.selarium.sigil.inactive": "Field inactive",
  "gui.selarium.sigil.mana": "Reserve: %s mana",
  "gui.selarium.sigil.quick_action": "Shift + click: toggle field",
  "gui.selarium.sigil.components": "Click to retrieve dusts",
  "message.selarium.sigil.owner_only": "Only the owner can change this sigil.",
  "message.selarium.sigil.deactivate_first": "Deactivate the sigil before changing its dusts.",
  "message.selarium.scroll.foreign": "This scroll belongs to another player.",
  "message.selarium.scroll.invalid": "This scroll is incomplete or its ward is disabled.",
  "message.selarium.scroll.not_discovered": "Activate this ward on a sigil before inscribing it.",
  "message.selarium.scroll.point_at_block": "Point at a block where the field should appear.",
  "message.selarium.scroll.duplicate": "You already maintain this ward through a scroll.",
  "message.selarium.scroll.limit": "Limit of two mobile or three fixed fields reached.",
  "message.selarium.scroll.unloaded": "The field location is not loaded yet.",
  "message.selarium.scroll.cast": "%s field invoked.",
  "message.selarium.attunement.own_sigil": "Use the scroll on your own sigil.",
  "message.selarium.attunement.inactive_sigil": "Deactivate the sigil before the ritual.",
  "message.selarium.attunement.tier_order": "This mana tier is not the next one to unlock.",
  "message.selarium.attunement.mana_spent": "More mana spent is required for this milestone.",
  "message.selarium.attunement.wards": "Activate more distinct wards for this milestone.",
  "message.selarium.attunement.refined": "Activate more refined wards for this milestone.",
  "message.selarium.attunement.success": "%s mana limit unlocked!",
  "message.selarium.phasing.available": "You can pass through Selarium phasing blocks.",
  "tooltip.selarium.scroll.creator": "Creator: %s",
  "tooltip.selarium.scroll.mobile": "Mobile field: follows its creator",
  "tooltip.selarium.scroll.fixed": "Fixed field: appears at the pointed location",
  "tooltip.selarium.scroll.duration": "Duration: %ss · upkeep: %s mana/cycle",
  "tooltip.selarium.attunement.limit": "New limit: %s mana",
  "tooltip.selarium.attunement.requirements": "Milestones: %s mana spent, %s wards, %s refined",
  "tooltip.selarium.attunement.cost": "Ritual: %s mana",
  "screen.selarium.warding_grimoire.overview.text": "The Grimoire controls who your sigils and scroll fields affect. Rules are shared by all wards of the same creator.",
  "screen.selarium.warding_grimoire.overview.safety": "Record a ward by activating it on a sigil before inscribing its scroll. Server safety settings have priority.",
  "screen.selarium.codex.start.title": "Getting Started",
  "screen.selarium.codex.start.p1": "Find Arcane Geodes underground. Mature clusters yield crystals; the Arcane Grinder turns crystals into Arcane Dust.",
  "screen.selarium.codex.start.p2": "Arcane Trees can mark a geode: follow the pale stone vein below the trunk. Arcane Petals offer a little dust near the surface.",
  "screen.selarium.codex.start.p3": "Use Arcane Dust on a sturdy block to create a sigil. Add specialized dusts to compose wards.",
  "screen.selarium.codex.start.p4": "All 32 wards remain available through sigils. The Inscription Bench adds scrolls and progression.",
  "screen.selarium.codex.mana.title": "Mana",
  "screen.selarium.codex.mana.p1": "Active wards pay upkeep in cycles. Payment uses the sigil reserve, adjacent tanks, then the owner's mana where allowed.",
  "screen.selarium.codex.mana.p2": "Your starting limit is 500. Successive rituals unlock 1,000, 2,500, 5,000 and 10,000; each tier requires milestones and mana.",
  "screen.selarium.codex.mana.p3": "Mana spent, discovered wards and unlocked tiers persist through death, dimension changes and restarts.",
  "screen.selarium.codex.grinder.title": "Arcane Grinder",
  "screen.selarium.codex.grinder.p1": "The Arcane Grinder turns crystals into Arcane Dust and combines dusts with reagents to make specialized variants.",
  "screen.selarium.codex.grinder.p2": "Refined wards require refined dust for every specialized component. Arcane Dust remains basic.",
  "screen.selarium.codex.recipes.title": "Core Recipes",
  "screen.selarium.codex.recipes.p1": "Paper, string and Arcane Dust make an Empty Scroll. Use it in the Inscription Bench with dusts and catalysts.",
  "screen.selarium.codex.recipes.p2": "Nine crystals make an Arcane Block. Arcane Crystal catalyzes basic wards; Arcane Block catalyzes refined wards.",
  "screen.selarium.codex.recipes.p3": "A book and Arcane Dust make the Codex. The Grimoire also needs Binding and Focus Dust.",
  "screen.selarium.codex.dusts.title": "Dusts",
  "screen.selarium.codex.dusts.p1": "Arcane is the base. Aegis protects; Vital sustains; Focus directs; Binding holds; Echo senses; Density anchors; Warp displaces; Veil conceals; Chrono bends timing.",
  "screen.selarium.codex.dusts.p2": "Basic recipes accept basic or refined dust. Refined recipes accept only refined specialized components.",
  "screen.selarium.codex.sigils.title": "Sigils",
  "screen.selarium.codex.sigils.p1": "Click a sigil without dust to choose among compatible wards. The interface shows requirements, range, cost and duration.",
  "screen.selarium.codex.sigils.p2": "Shift + click activates or deactivates the chosen ward. The interface also retrieves components, returning dust to inventory or the ground.",
  "screen.selarium.codex.sigils.p3": "A sigil belongs to its creator. A ward must be activated on a sigil before its scroll can be inscribed.",
  "screen.selarium.codex.progression.title": "Progression",
  "screen.selarium.codex.progression.p1": "1,000: spend 250 mana and activate 3 distinct wards. Inscribe basic Focus, Vital and Aegis with an Arcane Crystal. Ritual: 250 mana.",
  "screen.selarium.codex.progression.p2": "2,500: spend 1,200 mana and activate 6 wards, 2 refined. Inscribe refined Focus, Vital and Binding with a Blaze Rod and Arcane Block. Ritual: 700 mana.",
  "screen.selarium.codex.progression.p3": "5,000: spend 4,000 mana and activate 10 wards, 4 refined. Inscribe refined Warp, Veil and Focus with Dragon's Breath and an Ender Pearl. Ritual: 1,800 mana.",
  "screen.selarium.codex.progression.p4": "10,000: spend 10,000 mana and activate 16 wards, 8 refined. Inscribe refined Aegis, Echo and Chrono with a Nether Star and Echo Shard. Ritual: 4,000 mana.",
  "screen.selarium.codex.progression.p5": "Use an Attunement Scroll on your own inactive sigil. The ritual validates milestones again before charging mana.",
  "screen.selarium.codex.progression.p6": "The ritual can use the sigil reserve, adjacent tanks and owner mana, in that order. Failures preserve the scroll and mana.",
  "screen.selarium.codex.scrolls.title": "Scrolls",
  "screen.selarium.codex.scrolls.p1": "The Inscription Bench has an Empty Scroll slot, five dust slots, two catalyst slots and an output. Choose a recipe in its list.",
  "screen.selarium.codex.scrolls.p2": "A Ward Scroll requires a ward already activated by its creator. Inscribe its dusts with Arcane Crystal or Arcane Block.",
  "screen.selarium.codex.scrolls.p3": "Every scroll stores its creator's UUID. Only that player may use it. A valid cast consumes one scroll and the first mana charge.",
  "screen.selarium.codex.scrolls.p4": "Mobile fields follow their creator; the others appear where pointed. Limits: two mobile, three fixed and no duplicate ward.",
  "screen.selarium.codex.scrolls.p5": "The field lasts half a sigil's duration, pays the same upkeep and follows Grimoire rules. Its cooldown starts when it ends.",
  "screen.selarium.codex.scrolls.p6": "Mobile fields pause while offline, follow dimension changes and end on death. Fixed fields persist in the world until expiry.",
  "screen.selarium.codex.grimoire.title": "Grimoire",
  "screen.selarium.codex.grimoire.p1": "The Codex teaches; the Grimoire defines targets. Configure allies, enemies and entity categories before starting a field.",
  "screen.selarium.codex.grimoire.p2": "The Grimoire binds to an owner on first use and shares rules across their sigils and scrolls.",
  "screen.selarium.codex.grimoire.p3": "Shift + click creatures to record soul knowledge. Activating a ward records its pattern permanently.",
  "screen.selarium.codex.grimoire.p4": "Server safety settings, owner protection and allow/deny lists take priority over general rules.",
  "screen.selarium.codex.wards.title": "Wards",
  "screen.selarium.codex.wards.p1": "A ward is a continuous field. Each cycle pays upkeep and affects valid targets within range, subject to safety limits.",
  "screen.selarium.codex.wards.p2": "Recipes below show minimum purity, range, upkeep and interval. Missing dust, mana, permission or cooldown prevents activation.",
  "screen.selarium.codex.ward.entry": "%s: %s. Range %s, upkeep %s every %s ticks.",
  "screen.selarium.codex.tanks.title": "Mana Tanks",
  "screen.selarium.codex.tanks.p1": "Adjacent tanks sustain sigils and rituals after the sigil reserve. Mana fill is visible on all four sides.",
  "screen.selarium.codex.tanks.p2": "Scroll fields also use nearby mana sources and their creator's mana for upkeep.",
  "screen.selarium.codex.geodes.title": "Geodes",
  "screen.selarium.codex.geodes.p1": "Arcane Geodes contain stone, crystal blocks, budding blocks and four crystal growth stages.",
  "screen.selarium.codex.geodes.p2": "Mature clusters yield crystals when harvested; Silk Touch preserves the block. Fortune can increase crystals.",
  "screen.selarium.codex.geodes.p3": "Arcane Saplings grow ordinary trees. Player grown trees do not create new geodes.",
  "screen.selarium.codex.ward_note.ambient_mana": "Generates mana with a cap per activation.",
  "screen.selarium.codex.ward_note.whispering": "Alerts the owner to intruders.",
  "screen.selarium.codex.ward_note.spectral": "Reveals intruders with Glowing.",
  "screen.selarium.codex.ward_note.bulwark": "Grants resistance to allies.",
  "screen.selarium.codex.ward_note.rejuvenation": "Regenerates allies.",
  "screen.selarium.codex.ward_note.featherweight": "Reduces fall danger.",
  "screen.selarium.codex.ward_note.grounding": "Removes levitation and steadies allies.",
  "screen.selarium.codex.ward_note.magnetism": "Draws dropped items in.",
  "screen.selarium.codex.ward_note.banishment": "Moves intruders away from the field.",
  "screen.selarium.codex.ward_note.eclipse": "Darkens intruders' vision.",
  "screen.selarium.codex.ward_note.fertility": "Encourages animal breeding.",
  "screen.selarium.codex.ward_note.citadel": "Raises a temporary wall allies can pass through.",
  "screen.selarium.codex.ward_note.disruption": "Interrupts teleports.",
  "screen.selarium.codex.ward_note.cloaking": "Conceals the owner and clears hostile targets.",
  "screen.selarium.codex.ward_note.accelerating": "Speeds plants and young animals.",
  "screen.selarium.codex.ward_note.efficiency": "Speeds furnaces and the Arcane Grinder.",
  "screen.selarium.codex.ward_note.crushing": "Pressures and weakens intruders.",
  "screen.selarium.codex.ward_note.inversion": "Throws intruders upward.",
  "screen.selarium.codex.ward_note.aqualung": "Restores air and aids underwater movement.",
  "screen.selarium.codex.ward_note.transmutation": "Converts specific items and oxidizes copper.",
  "screen.selarium.codex.ward_note.tangible": "Forms a temporary barrier allies can cross.",
  "screen.selarium.codex.ward_note.sanctuary": "Prevents hostile spawns.",
  "screen.selarium.codex.ward_note.bounty": "May add one item to eligible drops.",
  "screen.selarium.codex.ward_note.immortal": "Prevents one allied death per 1,200 ticks for 200 extra mana.",
  "screen.selarium.codex.ward_note.drain": "Drains intruders with capped mana generation each cycle.",
  "screen.selarium.codex.ward_note.soul_chain": "Shares part of the damage among intruders.",
  "screen.selarium.codex.ward_note.stasis": "Slows intruders and projectiles.",
  "screen.selarium.codex.ward_note.maelstrom": "Pulls and suffocates intruders.",
  "screen.selarium.codex.ward_note.decay": "Applies decay to intruders.",
  "screen.selarium.codex.ward_note.deflection": "Deflects hostile projectiles.",
  "screen.selarium.codex.ward_note.silence": "Weakens and strips beneficial effects.",
  "screen.selarium.codex.ward_note.phasing": "Allows passage through Selarium phasing blocks."
}
'@
}

foreach ($locale in $translations.Keys) {
    $path = Join-Path $root "$locale.json"
    $existing = Get-Content -LiteralPath $path -Raw -Encoding utf8 | ConvertFrom-Json -AsHashtable
    $incoming = $translations[$locale] | ConvertFrom-Json -AsHashtable
    foreach ($key in $incoming.Keys) { $existing[$key] = $incoming[$key] }
    $existing | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $path -Encoding utf8
}
